name: open_at_login
description: A Flutter package to enable or disable launching desktop applications (macOS and Windows) automatically at user login.
version: 0.0.1
homepage: https://github.com/pavan-marthala/ai_keyboard/tree/master/packages/open_at_login
repository: https://github.com/pavan-marthala/ai_keyboard/tree/master/packages/open_at_login
issue_tracker: https://github.com/pavan-marthala/ai_keyboard/issues

topics:
  - macos
  - windows
  - launch-at-login
  - startup
  - desktop

platforms:
  macos:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: OpenAtLoginPluginCApi
